apiVersion: v1
kind: Service
metadata:
  name: Reddit-Application
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: Reddit-Application
